run:
  timeout: 3m
  go: "1.22"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - bodyclose
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: error-return
      - name: error-strings

issues:
  exclude-dirs:
    - bin
    - dist
