version: "2"
run:
  go: "1.25"
linters:
  enable:
    - bodyclose
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: error-return
        - name: error-strings
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - bin
      - dist
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - dist
      - third_party$
      - builtin$
      - examples$
