apiVersion: v1
kind: PersistentVolume
metadata:
  name: imgsync-e2e-localfs
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /srv/imgsync
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imgsync-e2e-localfs
  namespace: imgsync-e2e
spec:
  accessModes: [ReadWriteMany]
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
  volumeName: imgsync-e2e-localfs
