apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "imgsync.fullname" . }}
  labels:
    {{- include "imgsync.labels" . | nindent 4 }}
data:
  IMGSYNC_WORKERS:            "{{ .Values.worker.workers }}"
  IMGSYNC_IDLE_SLEEP_MIN:     "{{ .Values.worker.idleSleepMin }}"
  IMGSYNC_IDLE_SLEEP_MAX:     "{{ .Values.worker.idleSleepMax }}"
  IMGSYNC_FTP_HOST_MAX_CONNS: "{{ .Values.worker.ftpHostMaxConns }}"
  IMGSYNC_FTP_POOL_MAX_IDLE:  "{{ .Values.worker.ftpHostPoolMaxIdle }}"
  IMGSYNC_FTP_POOL_IDLE_TTL:  "{{ .Values.worker.ftpHostPoolIdleTTL }}"
  IMGSYNC_HEALTH_ADDR:        ":{{ .Values.health.port }}"
